language: java

dist: xenial

jdk:
  - openjdk8

# 'true' means do NOT do `mvn install`
# See https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: true

script: make build

deploy:
  provider: script
  # skip_cleanup is to keep the artifacts from the build phase
  skip_cleanup: true
  script: make ci-deploy

notifications:
  email:
    recipients:
      - stream-registry-committers@groups.homeawaycorp.com
    on_success: change
    on_failure: always

cache:
  directories:
  - "$HOME/.m2"